# Generated by Django 3.2.5 on 2021-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20210712_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='task',
        ),
        migrations.AddField(
            model_name='type',
            name='task',
            field=models.ManyToManyField(to='robots.Task'),
        ),
    ]
