# Generated by Django 3.2.5 on 2021-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20210712_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='Type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='robot',
            name='task',
            field=models.ManyToManyField(null=True, to='robots.Task'),
        ),
    ]
