# Generated by Django 3.2.5 on 2021-07-13 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_auto_20210713_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='task',
            field=models.ManyToManyField(to='robots.Task'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.type'),
        ),
    ]
