# Generated by Django 3.2.5 on 2021-07-13 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_auto_20210713_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.type'),
        ),
    ]
