# Generated by Django 3.2.5 on 2021-07-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0006_alter_robot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='task',
        ),
    ]
