# Generated by Django 3.2.5 on 2021-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0007_remove_robot_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='task',
            field=models.ManyToManyField(to='robots.Task'),
        ),
    ]
