# Generated by Django 3.2.5 on 2021-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0008_robot_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='type',
            name='task',
        ),
        migrations.AddField(
            model_name='type',
            name='avatar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='personality',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
